######### Basic Settings #########
basic:
    device: '2'
    seed: [1993]

    # Dataset Choises: cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cub200
    shuffle: false

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train

    logger_type: tensorboard

    note: lr0.01

######### Method's Hyperparameters #########
# special:

######### Experiment Settings for Datasets #########
options:
    cub200: 
        resnet18:
            epochs: 100 #80
            batch_size: 64
            num_workers: 8

            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0002
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [40, 70]
            lrate_decay: 0.1
            
