######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # 1, 50, 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin40
    shuffle: false # true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: adapter_cl
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: mcr
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    pretrain_path: logs/single_step/finetune_normal/pretrain_sd158/resnet18/pretrain_sd158_epoch200_lr0.0001/seed1_finetune_normal_pretrain_sd158_resnet18.pkl
    freeze_fe: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 80
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 8
    increment: 8
    
    logger_type: tensorboard
    
    note: sd158Pretrained_lr0.01_ft0.001

######### Method's Hyperparameters #########
special:
    incre_type: cil
    addition_dim: 1
    mode: special_adapter_v1|min_scores_test|min_others|use_alpha

    # mode options:
    # adapter type: | special_adapter_v1, channel_adapter_v1 |
    # test type: | min_scores_test, vote_test |
    # specific test type in 'min_scores_test': | min_others, min_taskID, min_mixed |

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin40:
        resnet18:
            img_size: 224
            
            layer_names: ['layer1', 'layer2', 'layer3', 'layer4'] # 'layer1', 'layer2', 'layer3', 'layer4'
            
            epochs: 200 # 200
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
            epochs_finetune: 100 # 50
            lrate_finetune: 0.001
            milestones_finetune: [55, 80]
        