######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin40
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: gmm_bayes
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    
    # test_epoch: 10

######### Method's Hyperparameters #########
special:
    incre_type: cil
    K: 2

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin40:
        resnet18:
            img_size: 224

            epochs: 1
            batch_size: 128
            num_workers: 4
            