######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    dataset: imagenet100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: icarl
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train
    save_pred_record: true
    # base10i10
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/icarl_cil_replay_herding/imagenet100/resnet18_b10i10/icarl_res18_manu_temp_20231123_175441"
    # base20i20
    checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/icarl_cil_replay_herding/imagenet100/resnet18_b20i20/icarl_res18"
    
    # base10i10_pretrainde
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/icarl_cil_replay_herding/imagenet100/resnet18_b10i10/icarl_res18_pretrained_20231209_170952"
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false # false
    sampling_method: herding # herding, random, closest_to_mean 

    apply_nme: true
    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20
    increment: 20
    prompt_num: 20
    top_k: 10
    manual_temp: false
    note: icarl_res18_pretrained

    # test_epoch: 40

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 1

######### Experiment Settings for Datasets #########
options:        
    imagenet100: 
        resnet18:
            epochs: 110 # 130
            batch_size: 32 # 128
            num_workers: 8

            opt_type: sgd
            lrate: 0.001 # 0.1
            weight_decay: 0.0005
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [49, 63, 90]
            lrate_decay: 0.1
            