######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin40
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: icarl
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: mcr
    openset_test: false

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    pretrain_path: logs/single_step/finetune_normal/pretrain_sd158/resnet18/pretrain_sd158_epoch200_lr0.0001/seed1_finetune_normal_pretrain_sd158_resnet18.pkl
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 80
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    apply_nme: true

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 8
    increment: 8
    
    note: sd158Pretrained_buffer80_lr0.001

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 2

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin40:
        resnet18:
            img_size: 224

            epochs: 200 # 200
            batch_size: 32
            num_workers: 4

            # opt_type: adam
            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
        