######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune, ssre
    method: fetril
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet32
    pretrained: false
    save_pred_record: false
    save_models: true # if true, programm will save model's weights during incremental train
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/icarl_cil_replay_herding/cifar100/resnet32_b10i10/icarl_manual_res32_20231121_205727"
    
    ######### Exampler Hyperparameters #########
    # memory_size: 0
    # fixed_memory: true
    # sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 50
    increment: 10
    prompt_num: 10
    top_k: 5
    manual_temp: true

    note: fetril_manual_res18

######### Method's Hyperparameters #########
special:
    incre_type: cil

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            init_epochs: 200
            init_lrate : 0.1

            img_size: 32
            epochs: 50 #170
            batch_size: 128
            num_workers: 8
            
            opt_type: sgd
            lrate: 0.05
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: cos
            lrate_decay: 0.2

        resnet18_rep:
            epochs: 101 #170
            batch_size: 128
            num_workers: 4
            
            opt_type: adam
            lrate: 0.1 #0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [49, 63, 90]
            lrate_decay: 0.2
