######### Basic Settings #########
basic:
    device: '0'
    seed: [1, 42] # 1, 50, 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: medmnist_hr
    shuffle: false # true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, mcr
    eval_metric: mcr

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    freeze_fe: false
    save_models: true # if true, programm will save model's weights during incremental train
    
    note: pretrained_lr0.01_mcr
    # test_epoch: 10

######### Method's Hyperparameters #########
# special:

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    medmnist_hr:
        resnet18:
            img_size: 224

            epochs: 200 # 340
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            