######### Basic Settings #########
basic:
    device: '2'
    seed: [50, 100] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dual_prompt
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: vit_base_patch16_224 # not used
    pretrained: true # not used
    freeze_fe: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 2
    increment: 2
    
    note: lr0.001_epoch120

######### Method's Hyperparameters #########
special:
    incre_type: cil
    e_prompt_pool: 10
    e_prompt_length: 20
    g_prompt_length: 6

######### Experiment Settings for Datasets #########
options:
    # experiment settings for skin8
    skin8: 
        vit_base_patch16_224:
            img_size: 224

            epochs: 120 #20
            batch_size: 32
            num_workers: 4            

            opt_type: adam
            lrate: 0.001
            scheduler: cos
            
