######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dynamic_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    apply_nme: false

    # Backbone Choises: resnet18 , resnet18_cifar
    backbone: resnet18
    pretrained: true # false
    save_models: true # if true, programm will save model's weights during incremental train
    #base10i10
    checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dynamic_er_cil_replay_herding/cifar100/resnet32_b10i10/der_res32_cifar_20231125_175921"
    #base20i20
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dynamic_er_cil_replay_herding/cifar100/resnet32_b20i20/der_res32_cifar_b0i20"
    #base50i50
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dynamic_er_cil_replay_herding/cifar100/resnet32_b50i50/der_res32_cifar"
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20 # 10
    increment: 20 # 10
    prompt_num: 10
    top_k: 5
    manual_temp: true
    note: der_res18

    # logger_type: tensorboard

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            epochs: 170 # 170
            batch_size: 32 # 64
            num_workers: 4

            opt_type: sgd
            lrate: 0.1 # 0.5
            weight_decay: 0.0005
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [80, 120, 150]
            lrate_decay: 0.1

            epochs_finetune: 30 # 200
            lrate_finetune: 0.1 # 0.5
            milestones_finetune: [15]
        
        resnet18_cifar:
            epochs: 150 #170
            batch_size: 32
            num_workers: 4
            img_size: 224
            
            opt_type: sgd
            lrate: 0.1
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [80, 120, 140]
            lrate_decay: 0.1

            epochs_finetune: 30 # 200
            lrate_finetune: 0.1 # 0.5
            milestones_finetune: [15]

        resnet18:
            img_size: 224

            epochs: 110 # 200
            batch_size: 128
            num_workers: 4
            
            # opt_type: adam
            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [49, 63, 90]
            lrate_decay: 0.1

            epochs_finetune: 30 # 200
            lrate_finetune: 0.001 # 0.5
            milestones_finetune: [15]