######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    dataset: imagenet100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dynamic_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train
    
    # base10i10
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dynamic_er_cil_replay_herding/imagenet100/resnet18_b10i10/der_res18_manu_temp_20231122_113022"
    # base20i20
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dynamic_er_cil_replay_herding/imagenet100/resnet18_b20i20/der_res18/"
    
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false # false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20
    increment: 20
    prompt_num: 3
    top_k: 5
    manual_temp: true
    note: der_res18_pretrained

    # test_epoch: 40

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 1

######### Experiment Settings for Datasets #########
options:        
    imagenet100: 
        resnet18:
            img_size: 224

            epochs: 100 # 200
            batch_size: 128
            num_workers: 4
            
            # opt_type: adam
            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [49, 63, 90]
            lrate_decay: 0.1

            epochs_finetune: 60 # 200
            lrate_finetune: 0.1 # 0.5
            milestones_finetune: [15,30,45]