######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: imagenet_r
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dark_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: mcr

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: false # false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: reservoir # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20
    increment: 20
    prompt_num: 20
    top_k: 5
    manual_temp: true
    note: darkerpp_0424_old-ir

######### Method's Hyperparameters #########
special:
    incre_type: cil
    alpha: 0.1 # 0.1
    beta: 0.5 # 0.5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    imagenet_r: 
        resnet18:
            img_size: 224

            epochs: 200 # 170
            batch_size: 128
            num_workers: 4

            opt_type: sgd
            lrate: 0.1
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
        
        vit_base_patch16_224:
            img_size: 224

            epochs: 50 # 170
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.003
            
            scheduler: multi_step
            milestones: [35, 45]
            lrate_decay: 0.1
            
            