######### Basic Settings #########
basic:
    device: '0'
    seed: [50] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: medmnist_hr
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dark_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: mcr

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: true # false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 330
    fixed_memory: false
    sampling_method: reservoir # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true

    note: derpp_buffer330_lr0.003_b32_beta0.5_mcr_order2

######### Method's Hyperparameters #########
special:
    incre_type: cil
    alpha: 0.1
    beta: 0.5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    medmnist_hr: 
        resnet18:
            img_size: 224

            epochs: 50 # 170
            batch_size: 32
            num_workers: 8

            opt_type: sgd
            lrate: 0.003
            
            scheduler: multi_step
            milestones: [35, 45]
            lrate_decay: 0.1
            
            