######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: imagenet100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dark_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: false # false
    save_models: true # if true, programm will save model's weights during incremental train
    # base10i10
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dark_er_cil_replay_reservoir/imagenet100/resnet18_b10i10/der_pp_manu_temp"
    # base20i20
    checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/dark_er_cil_replay_reservoir/imagenet100/resnet18_b20i20/der_pp_20231205_211952"
    
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: reservoir # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20
    increment: 20
    prompt_num: 10
    top_k: 10
    manual_temp: false
    note: der_pp

######### Method's Hyperparameters #########
special:
    incre_type: cil
    alpha: 0.1
    beta: 0.5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    imagenet100: 
        resnet18:
            img_size: 224

            epochs: 150 # 50
            batch_size: 32
            num_workers: 8  
            
            opt_type: sgd
            lrate: 0.1 # 0.03
            weight_decay: 0
            opt_mom: 0

            scheduler: multi_step
            milestones: [55, 90, 130]
            lrate_decay: 0.1
            