######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: clip_cil
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: vit_base_patch16_224_clip
    pretrained: true
    freeze_fe: true
    save_models: true # if true, programm will save model's weights during incremental train

    apply_nme: true

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    
    note: bce_loss

######### Method's Hyperparameters #########
special:
    incre_type: cil
    prompt_length: 16

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100:        
        vit_base_patch16_224_clip:
            img_size: 224

            epochs: 100 # 200
            batch_size: 32 # 64
            num_workers: 8
            
            # opt_type: adam
            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
