######### Basic Settings #########
basic:
    device: '5'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: ucir
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: cosine_resnet32
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train
    # b10i10
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/ucir_cil_replay_herding/cifar100/cosine_resnet32_b10i10/urcr_res32_manu_temp_20231124_123929"
    # b20i20
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/ucir_cil_replay_herding/cifar100/cosine_resnet32_b20i20/urcr_base20i20"
    # b50i50
    # checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/ucir_cil_replay_herding/cifar100/cosine_resnet32_b50i50/urcr_base50i50"
    
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: true # true, as the paper reported
    sampling_method: herding # herding, random, closest_to_mean

    apply_nme: false

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    prompt_num: 10
    top_k: 5
    manual_temp: true
    note: ucir_base50i50

######### Method's Hyperparameters #########
special:
    incre_type: cil
    # cifar100
    lambda_base: 5 # based on dataset
    K: 2 # for all experiments
    margin: 0.5 # for all experiments
    nb_proxy: 1

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        cosine_resnet32:
            epochs: 160
            batch_size: 32 # 128
            num_workers: 4

            opt_type: sgd
            lrate: 0.1
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [80, 120]
            lrate_decay: 0.1
        
        resnet18_cifar:
            epochs: 120 #170
            batch_size: 32
            num_workers: 4
            img_size: 224
            
            opt_type: sgd
            lrate: 0.1
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [49, 63, 90]
            lrate_decay: 0.2