######### Basic Settings #########
basic:
    device: '8'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: imagenet100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: ucir
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: cosine_resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train
    save_pred_record: true

    # base10i10
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/ucir_cil_replay_herding/imagenet100/cosine_resnet18_b10i10/urcr_res18_manu_temp/"
    # base20i20
    #checkpoint_dir: "/home/21/zejun/Storage/CL_code/IL_Framework/logs/multi_step/ucir_cil_replay_herding/imagenet100/cosine_resnet18_b20i20/urir_res18"
    
    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: true # true, as the paper reported
    sampling_method: herding # herding, random, closest_to_mean

    apply_nme: false

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    prompt_num: 10
    top_k: 5
    manual_temp: true
    note: ucir_r18_pretrained

######### Method's Hyperparameters #########
special:
    incre_type: cil
    # ImageNet1000
    lambda_base: 10
    K: 2
    margin: 0.5
    nb_proxy: 1
    

######### Experiment Settings for Datasets #########
options:    
    imagenet1000: 
        cosine_resnet18:
            epochs: 90 #170
            batch_size: 64 # 128
            num_workers: 8

            opt_type: sgd
            lrate: 0.1
            weight_decay: 0.0001
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [30, 60]
            lrate_decay: 0.1
    
    imagenet100: 
        cosine_resnet18:
            epochs: 110 #90
            batch_size: 128 # 128
            num_workers: 16

            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0001
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [30, 60,90]
            lrate_decay: 0.1
