######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: moe_v1
    method_type: single_step
    # eval_metric Choises: acc, recall
    eval_metric: mcr

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18 # not used
    pretrained: true # not used
    freeze_fe: true
    save_models: true # if true, programm will save model's weights during incremental train
    
    # for more efficient experiment
    # split_dataset: true
    # init_cls: 10
    # increment: 10

    note: e1t1_conv1x1FMCompress_ActBN_kernel3_lr0.001

######### Method's Hyperparameters #########
special:
    expert_per_task: 1
    topk: 1
    expert_kernel_num: 3
    mode: moe_v1|conv1x1_fm_compress|activate_bn

    # mode option(without space)
    # add adapter option
    # moe type: | moe_v1 |
    # feature map sourse of the gate: | gate_w_pretrain_fm | (if not appear, use previous fm directly)
    # feature map compress type in gate: | conv1x1_fm_compress, avg_fm_compress |
    # activate bn in feature extractor or not: | activate_bn | (if not appear, BNs will be freezed)

######### Experiment Settings for Datasets #########
options:
    # experiment settings for skin8
    skin8: 
        resnet18:
            img_size: 224

            layer_names: ['layer1', 'layer2', 'layer3', 'layer4']

            epochs: 200 #20
            batch_size: 64 # 128
            num_workers: 4            

            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
